import React,{useEffect,useState} from "react";
import { DrizzleContext } from "@drizzle/react-plugin";
import { Drizzle } from "@drizzle/store";
import drizzleOptions from "./drizzleOptions";
// import MyComponent from "./MyComponent";
import Web3 from 'web3';
import "./App.css";


// components
import {Typography,notification,message} from 'antd';
import FlightForm from "./components/flightForm/flightForm.js";
import OperationStatus from "./components/operationStatus/index";
import FlightReport from './components/flightReport/index'
import Airlines from './components/airlines/index'
import Header from './components/header/header'

// config
import Config from './config.json'
import FlightSuretyApp from './contracts/FlightSuretyApp'
import FlightSuretyData from './contracts/FlightSuretyData'
import data from './data.json'

const { Title } = Typography;

  let flightSuretyApp;
  let flightSuretyData;
  
  const App = () => {
    
    const [rand,setRand] = useState(5);

  // const [flightSuretyApp, setFlightSuretyApp] = useState({});
  const [passengers, setPassengers] = useState([])
  const [airlines, setAirlines] = useState([])
  const [flights, setFlights] = useState([])
  const [owner, setOwner] = useState('')
  const [firstAirline, setFirstAirline] = useState();

  const [operationalStatus, setOperationalStatus] = useState(false);

  const setupPassengers = (accounts) =>{
    
    let passengerData = [];
    const passengerNames = data['passengers'];
    for(let i=0; i<accounts.length; i++){
      passengerData.push({
        name:passengerNames[i],
        address:accounts[i]
      })
    }
    setPassengers(passengerData);
  }

  const setupAirlines = (accounts) =>{

    const airlineNames = data['airlines'];
    console.log(airlineNames);

    let airlinesData=[];
    for(let i = 0; i <= data['airlines'].length-1; i++){
      // console.log(accounts[i])
      airlinesData.push({
        address: accounts[i],
        name: airlineNames[i],
      })
    }
    setAirlines(airlinesData);
  }

  const setupFlights = (accounts) =>{

    let flightsData = [];
    for(let i=0; i<accounts.length; i++){
      
     let flight = data['flights'][i].flight;
     let timestamp = data['flights'][i].timestamp;
      
      flightsData.push({
        flight:flight,
        timestamp:timestamp,
        airlineAddress:  accounts[i]
      });

    }
    setFlights(flightsData);
  }

  const setupOwner = (account) =>{
    setOwner(account);
  }

  const setupFirstAirline = (address) =>{
    setFirstAirline(address);
  }

  const fetchOperationalStatus = async()=>{
    let operationalStatus = await flightSuretyApp.methods.isOperational().call();
    setOperationalStatus(operationalStatus);
   }


  const connectToContract = async()=>{
    const config = Config['localhost'];
    const web3 = new Web3(new Web3.providers.HttpProvider(config.url));

    // connect to data and app contract
    flightSuretyApp =  new web3.eth.Contract(FlightSuretyApp.abi, config.appAddress);
    flightSuretyData =  new web3.eth.Contract(FlightSuretyData.abi, config.dataAddress);

    const firstAirlineAddress = await flightSuretyData.methods.firstAirlineAddress().call();
    const result =  await flightSuretyData.methods.registeredAirlinesCount().call();
    console.log(result)
    
    // fetch all accounts created by ganache
    const accounts = await web3.eth.getAccounts(); 
    
    const firstAirline = accounts[0];
    const airlineAccounts = accounts.slice(0,5);
    const passengerAccounts = accounts.slice(11,17);
    const flightAccounts = accounts.slice(1,4);

    // Both the owner and the first airline uses the same address
    // which is the first account generated by ganache
    setupFirstAirline(firstAirlineAddress);
    setupOwner(firstAirline);

    setupAirlines(airlineAccounts);
    setupPassengers(passengerAccounts);
    setupFlights(flightAccounts);

  }



  useEffect(() => {
    console.log('Initializing contract ...')
    connectToContract()
    fetchOperationalStatus()
    return () => {
    };
  }, [])
  

        return (
          <div className="app">
            <div className="layout">

              <Header/>
              <OperationStatus
                status = {operationalStatus}
                />

              <FlightForm
               title={'Insurance'}
               flights={flights}
               passengers = {passengers}
               btnLabel={'Buy Insurance 1ETH'}
               flightSuretyApp = {flightSuretyApp}
               />

              <FlightForm
                title={'FlightStatus'}
                flights={flights}
                passengers = {passengers}
                flightSuretyApp = {flightSuretyApp}
                btnLabel={'Check Flight Status'}
                rand={rand}
                />
              {/* <FlightReport/> */}
              <Airlines
               airlines={airlines}
               flightSuretyApp = {flightSuretyApp}
               owner ={owner}
               firstAirline ={firstAirline}
               />
            </div>
          </div>
          )
          }


export default App;
